"""
ResearchForge DOCX Exporter
Generates a .docx report with real document structure (headings, body
paragraphs, a references section) from completed report state.

Consumes the same state contract as the other exporters via
extract_report_parts(), so all four export formats render identical report
content. Everything model-generated lands as plain text runs — python-docx
never interprets markup, which keeps model output inert.
"""

import logging

from docx import Document
from docx.shared import Pt

from export.markdown_exporter import extract_report_parts

logger = logging.getLogger(__name__)


def _confidence_paragraph(document: Document, confidence: float) -> None:
    text = (
        f"Generated by ResearchForge · overall confidence: {round(confidence * 100)}%"
    )
    paragraph = document.add_paragraph(text)
    paragraph.runs[0].font.size = Pt(9)


def build_docx_report(state: dict, output_path: str) -> str:
    """
    Render the completed report as a DOCX file at ``output_path``.

    Returns the output path (same contract as the PDF exporter). Raises
    ValueError when the state has no written sections — endpoint callers
    map that to a 400 response.
    """
    parts = extract_report_parts(state)

    document = Document()
    document.add_heading(parts["topic"], level=0)

    _confidence_paragraph(document, parts["overall_confidence"])

    for section in parts["sections"]:
        document.add_heading(f"{section['number']}. {section['title']}", level=1)
        for paragraph_text in section["content"].split("\n\n"):
            if paragraph_text.strip():
                document.add_paragraph(paragraph_text.strip())
        if section["sources_used"]:
            sources_line = document.add_paragraph(
                f"Sources: {', '.join(section['sources_used'])}"
            )
            sources_line.runs[0].font.size = Pt(9)

    if parts["sources"]:
        document.add_heading(f"References ({len(parts['sources'])})", level=1)
        for source in parts["sources"]:
            number = source["citation_number"]
            label = f"[{number}] " if number is not None else ""
            provenance = ""
            if source.get("persistent_ids"):
                ids = ", ".join(f"{k}: {v}" for k, v in sorted(source["persistent_ids"].items()))
                provenance = f" ({ids})"
            elif source.get("domain"):
                provenance = f" ({source['domain']})"
            document.add_paragraph(f"{label}{source['title']}{provenance}")

    document.save(output_path)
    logger.info("DOCX exported: %s", output_path)
    return output_path
