"""
ResearchForge Markdown/HTML Exporter
Generates Markdown and standalone-HTML reports from completed report state.

Consumes the same state contract as the PDF exporter (written_sections,
sources, confidence_scores, overall_confidence) so all three export formats
render identical report content. HTML output escapes every dynamic value —
report content is model-generated and must never be interpolated raw.
"""

import html
import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def extract_report_parts(state: dict) -> dict:
    """
    Pull the report fields the exporters render out of session state.

    Pure function. Raises ValueError when the state has no written sections —
    endpoint callers map that to a 400 response.
    """
    written_sections = state.get("written_sections") or []
    if not written_sections:
        raise ValueError("No written sections found in report")

    sections = []
    for index, section in enumerate(written_sections, start=1):
        content = (section.get("content") or "").strip()
        sections.append(
            {
                "number": index,
                "title": (section.get("title") or f"Section {index}").strip(),
                "content": content,
                "sources_used": section.get("sources_used") or [],
            }
        )

    sources = []
    for source in state.get("sources") or []:
        sources.append(
            {
                "citation_number": source.get("citation_number"),
                "title": (source.get("title") or source.get("url") or "Untitled source").strip(),
                "url": (source.get("url") or "").strip(),
                "domain": (source.get("domain") or "").strip(),
            }
        )

    return {
        "topic": (state.get("topic") or "").strip() or "Research Report",
        "depth": state.get("depth", "quick"),
        "overall_confidence": state.get("overall_confidence", 0.0),
        "sections": sections,
        "sources": sources,
        "generated_at": datetime.now(timezone.utc),
    }


def build_markdown_report(state: dict) -> str:
    """Render the completed report as a Markdown document."""
    parts = extract_report_parts(state)

    confidence_pct = round(parts["overall_confidence"] * 100)
    lines = [
        f"# {parts['topic']}",
        "",
        (
            f"*Generated by ResearchForge on "
            f"{parts['generated_at'].strftime('%Y-%m-%d %H:%M UTC')} · "
            f"depth: {parts['depth']} · overall confidence: {confidence_pct}%*"
        ),
        "",
    ]

    for section in parts["sections"]:
        lines.append(f"## {section['number']}. {section['title']}")
        lines.append("")
        lines.append(section["content"])
        lines.append("")
        if section["sources_used"]:
            lines.append(f"*Sources: {', '.join(section['sources_used'])}*")
            lines.append("")

    if parts["sources"]:
        lines.append(f"## References ({len(parts['sources'])})")
        lines.append("")
        for source in parts["sources"]:
            number = source["citation_number"]
            label = f"{number}. " if number is not None else "- "
            if source["url"]:
                title_fragment = f"[{source['title']}]({source['url']})"
            else:
                title_fragment = source["title"]
            domain_suffix = f" — {source['domain']}" if source["domain"] else ""
            lines.append(f"{label}{title_fragment}{domain_suffix}")

    return "\n".join(lines).rstrip() + "\n"


def build_html_report(state: dict) -> str:
    """Render the completed report as a standalone HTML document."""
    parts = extract_report_parts(state)
    esc = html.escape

    sections_html = []
    for section in parts["sections"]:
        paragraphs = "".join(
            f"<p>{esc(paragraph.strip())}</p>"
            for paragraph in section["content"].split("\n\n")
            if paragraph.strip()
        )
        sources_line = ""
        if section["sources_used"]:
            sources_line = (
                f'<p class="section-sources">Sources: '
                f"{esc(', '.join(section['sources_used']))}</p>"
            )
        sections_html.append(
            "<section class='report-section'>"
            f"<h2>{section['number']}. {esc(section['title'])}</h2>"
            f"{paragraphs}{sources_line}"
            "</section>"
        )

    references_html = []
    for source in parts["sources"]:
        title = esc(source["title"])
        if source["url"]:
            references_html.append(
                f"<li><a href=\"{esc(source['url'])}\">{title}</a>"
                + (f" <span class='domain'>({esc(source['domain'])})</span>" if source["domain"] else "")
                + "</li>"
            )
        else:
            references_html.append(f"<li>{title}</li>")

    confidence_pct = round(parts["overall_confidence"] * 100)
    references_block = (
        (
            "<section class='references'><h2>References "
            f"({len(parts['sources'])})</h2><ol>{''.join(references_html)}</ol></section>"
        )
        if parts["sources"]
        else ""
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(parts['topic'])}</title>
<style>
  body {{ font-family: Georgia, 'Times New Roman', serif; max-width: 800px;
         margin: 2rem auto; padding: 0 1.5rem; color: #1a1a2e; line-height: 1.6; }}
  h1 {{ font-size: 2rem; margin-bottom: 0.25rem; }}
  h2 {{ font-size: 1.35rem; margin-top: 2rem; border-bottom: 1px solid #e2e8f0;
       padding-bottom: 0.3rem; }}
  .meta {{ color: #718096; font-size: 0.9rem; margin-bottom: 2rem; }}
  .report-section p {{ margin: 0.75rem 0; }}
  .section-sources {{ font-size: 0.85rem; color: #4a5568; font-style: italic; }}
  .references li {{ margin: 0.4rem 0; font-size: 0.95rem; }}
  .domain {{ color: #718096; font-size: 0.85rem; }}
  a {{ color: #4f46e5; }}
</style>
</head>
<body>
<h1>{esc(parts['topic'])}</h1>
<p class="meta">Generated by ResearchForge on
{parts['generated_at'].strftime('%Y-%m-%d %H:%M UTC')} · depth: {esc(parts['depth'])} ·
overall confidence: {confidence_pct}%</p>
{''.join(sections_html)}
{references_block}
</body>
</html>
"""
